# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hwtBP_PzQ1EcSr4QJeEr1SQiAqDz6UPe
"""

import pandas as pd



data1={ "Name": ["Braund, Mr. Owen Harris","Allen, Mr. William Henry","Bonnell, Miss. Elizabeth"],
 "Age": [22, 35, 58],
 "Gender": ["male", "male", "female"]
}

data1

type(data1)

df=pd.DataFrame(data=data1)

df

type(df)

name=df['Name']

type(name)

name

ages=pd.Series([22,23,54], name="Age")

ages

df

df['Age'].max()

ages.max(
)

df.describe()

country = ["Brazil", "Russia", "India", "China", "South Africa"]
capital = ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"]
area = [8.516, 17.10, 3.286, 9.67, 2.98]
population = [200.4, 143.5, 1252, 133, 4.3]

import pandas as pd

brics=pd.DataFrame(data={'country': country,
                  'capital': capital,
                  'area': area,
                  'population': population})

brics

brics.shape

brics.index

brics.index=['A','B','C','D','E']

brics

brics.index=range(1,10
              ,2)

brics

brics.columns

c=brics.country

type(c)

brics

brics.country

c

brics[['country']]

a=brics.population

type(a)

brics.index=['A','B','C','D','E']

brics

a

type(a)

brics.index

brics.set_index("country")

brics

brics=brics.set_index("country")

brics

brics.reset_index()

brics

brics.reset_index(inplace=True)

brics

v

brics.set_index("country", inplace = True)

brics

brics.set_index('area')

brics.reset_index()

brics.set_index("area", inplace=True)

brics



brics.reset_index()

brics

country = ["Brazil", "Russia", "India", "China", "South Africa"]
capital = ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"]
area = [8.516, 17.10, 3.286, 9.67, 2.98]
population = [200.4, 143.5, 1252, 133, 4.3]

brics=pd.DataFrame(data={'country': country,
                  'capital': capital,
                  'area': area,
                  'population': population})

brics

brics.columns = range(4)

brics



type(brics.columns)

b=list(brics.columns)

type(b)

b[1]='capital'

brics.columns=b

brics

brics.rename(columns={'country':'count','area':'ar'} , inplace=True)

brics

country = ["Brazil", "Russia", "India", "China", "South Africa"]
capital = ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"]
area = [8.516, 17.10, 3.286, 9.67, 2.98]
population = [200.4, 143.5, 1252, 133, 4.3]

brics=pd.DataFrame(data={'country': country,
                  'capital': capital,
                  'area': area,
                  'population': population})

brics

brics.rename(columns={'country':'count','area':'ar'} , inplace=True)

brics

brics.rename(index={1:'ullu',2:'patha'}, inplace =True)

brics

