# -*- coding: utf-8 -*-
"""panda_part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17HwooJe35oP0iisqJd4nAdJt2YW08Y_G
"""

import pandas as pd

pd.__version__

games=pd.read_csv("vgsalesGlobale.csv")

games

games.head()

games.dtypes

games.head(10
           )

games.Genre

games.Year

games.Genre.describe()

games.Genre.value_counts()

games.Genre.value_counts(normalize=True)

games.Genre.value_counts().head()

games.Genre.unique()

games.Genre.nunique()

pd.crosstab(games.Genre, games.Year)

